// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jlnyfoionybxjhuqtbrk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impsbnlmb2lvbnlieGpodXF0YnJrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1MzU5NDMsImV4cCI6MjA2OTExMTk0M30.WiVzCwrMXaQlGRPZAFo39tDTyORUjrWq-zoMDUV_zNo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});